# Generated by Django 2.1 on 2018-08-10 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20180810_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
